// Static require map — React Native needs static require() at build time
const IMAGES = {
  'Akshy-tritiya':         require('../../assets/panjika/Akshy-tritiya.webp'),
  'Ambubachi':             require('../../assets/panjika/Ambubachi.webp'),
  'Bhai-fota':             require('../../assets/panjika/Bhai-fota.webp'),
  'Bheemrao-Ambedkar':     require('../../assets/panjika/Bheemrao-Ambedkar.webp'),
  'Bhoot-chaturdshi':      require('../../assets/panjika/Bhoot-chaturdshi.webp'),
  'Buddh-Purnima':         require('../../assets/panjika/Buddh-Purnima.webp'),
  'Charak-puja':           require('../../assets/panjika/Charak-puja.webp'),
  'Chhath-puja':           require('../../assets/panjika/Chhath-puja.webp'),
  'Dhanteras':             require('../../assets/panjika/Dhanteras.webp'),
  'Dol-Purnima':           require('../../assets/panjika/Dol-Purnima.webp'),
  'Durga-Puja':            require('../../assets/panjika/Durga-Puja.webp'),
  'Ganesh-Chaturthi':      require('../../assets/panjika/Ganesh-Chaturthi.webp'),
  'Ganga-dashara':         require('../../assets/panjika/Ganga-dashara.webp'),
  'Geeta-Jayanti':         require('../../assets/panjika/Geeta-Jayanti.webp'),
  'Guru-Purnima':          require('../../assets/panjika/Guru-Purnima.webp'),
  'Hanuman-Jayanti':       require('../../assets/panjika/Hanuman-Jayanti.webp'),
  'Harichand-Thakur':      require('../../assets/panjika/Harichand-Thakur.webp'),
  'Hartalika-teej':        require('../../assets/panjika/Hartalika-teej.webp'),
  'Holika-Dahan':          require('../../assets/panjika/Holika-Dahan.webp'),
  'Independent-Days':      require('../../assets/panjika/Independent-Days.webp'),
  'Jamai-sasthi':          require('../../assets/panjika/Jamai-sasthi.webp'),
  'Jhulan-Jatra':          require('../../assets/panjika/Jhulan-Jatra.webp'),
  'Kali-Puja':             require('../../assets/panjika/Kali-Puja.webp'),
  'Krishna-ekadashi':      require('../../assets/panjika/Krishna-ekadashi.webp'),
  'Krishnashtami':         require('../../assets/panjika/Krishnashtami.webp'),
  'Lokkhi-Puja':           require('../../assets/panjika/Lokkhi-Puja.webp'),
  'Maghi-Purnima':         require('../../assets/panjika/Maghi-Purnima.webp'),
  'Mahalaya':              require('../../assets/panjika/Mahalaya.webp'),
  'Mahatma-Gandhi':        require('../../assets/panjika/Mahatma-Gandhi.webp'),
  'Monosha-Puja':          require('../../assets/panjika/Monosha-Puja.webp'),
  'Nazrul-Islam':          require('../../assets/panjika/Nazrul-Islam.webp'),
  'Neel-Sasti':            require('../../assets/panjika/Neel-Sasti.webp'),
  'Netaji-Subhash-Chandra':require('../../assets/panjika/Netaji-Subhash-Chandra.webp'),
  'Pahla-baisakh':         require('../../assets/panjika/Pahla-baisakh.webp'),
  'Pous-Sankranti':        require('../../assets/panjika/Pous-Sankranti.webp'),
  'Prajatantra-Divas':     require('../../assets/panjika/Prajatantra-Divas.webp'),
  'Rabindra-Jayanti':      require('../../assets/panjika/Rabindra-Jayanti.webp'),
  'Rakhi-Purnima':         require('../../assets/panjika/Rakhi-Purnima.webp'),
  'Ramnavami':             require('../../assets/panjika/Ramnavami.webp'),
  'Rash-Purnima':          require('../../assets/panjika/Rash-Purnima.webp'),
  'Rath-Yatra':            require('../../assets/panjika/Rath-Yatra.webp'),
  'Saraswati-Puja':        require('../../assets/panjika/Saraswati-Puja.webp'),
  'Shukla-ekadashi':       require('../../assets/panjika/Shukla-ekadashi.webp'),
  'Swami-Vivekananda':     require('../../assets/panjika/Swami-Vivekananda.webp'),
  'Tulsi-vivah':           require('../../assets/panjika/Tulsi-vivah.webp'),
  'Vidyasagar':            require('../../assets/panjika/Vidyasagar.webp'),
  'Vishwakarma-puja':      require('../../assets/panjika/Vishwakarma-puja.webp'),
  'loknath-puja':          require('../../assets/panjika/loknath-puja.webp'),
  'ramakrishna':           require('../../assets/panjika/ramakrishna.webp'),
  'shiva-ratri':           require('../../assets/panjika/shiva-ratri.webp'),
};

export default IMAGES;
